"""
QBO AccountSubType → IRS Form 1065 line mapping.
"""

FORM_1065_LINES = {
    "1a": "Gross receipts or sales",
    "1b": "Returns and allowances",
    "2": "Cost of goods sold (Schedule A, line 8)",
    "3": "Gross profit (line 1a - 1b - 2)",
    "4": "Ordinary income (loss) from other partnerships",
    "5": "Net farm profit (loss)",
    "6": "Net gain (loss) from Form 4797",
    "7": "Other income (loss)",
    "8": "Total income (loss)",
    "9": "Salaries and wages",
    "10": "Guaranteed payments to partners",
    "11": "Repairs and maintenance",
    "12": "Bad debts",
    "13": "Rent",
    "14": "Taxes and licenses",
    "15": "Interest",
    "16a": "Depreciation",
    "17": "Depletion",
    "18": "Retirement plans, etc.",
    "19": "Employee benefit programs",
    "20": "Other deductions (attach statement)",
    "21": "Total deductions",
    "22": "Ordinary business income (loss)",
}

QBO_SUBTYPE_TO_1065: dict[str, tuple[str, str]] = {
    # Income
    "SalesOfProductIncome": ("1a", "Gross receipts"),
    "ServiceFeeIncome": ("1a", "Gross receipts"),
    "OtherPrimaryIncome": ("1a", "Gross receipts"),
    "NonProfitIncome": ("1a", "Gross receipts"),
    "DiscountsRefundsGiven": ("1b", "Returns and allowances"),
    "OtherMiscellaneousIncome": ("7", "Other income"),
    "UnrealisedLossOnSecuritiesNetOfTax": ("7", "Other income"),
    "OtherInvestmentIncome": ("7", "Other income"),
    "TaxExemptInterest": ("K-18a", "Tax-exempt interest"),
    # COGS
    "SuppliesMaterialsCogs": ("2-purchases", "COGS: Purchases"),
    "CostOfLaborCos": ("2-labor", "COGS: Cost of labor"),
    "EquipmentRentalCos": ("2-other", "COGS: Other costs"),
    "OtherCostsOfServiceCos": ("2-other", "COGS: Other costs"),
    "ShippingFreightDeliveryCos": ("2-other", "COGS: Other costs"),
    # Expenses
    "PayrollExpenses": ("9", "Salaries and wages"),
    "RepairMaintenance": ("11", "Repairs and maintenance"),
    "BadDebts": ("12", "Bad debts"),
    "RentOrLeaseOfBuildings": ("13", "Rent"),
    "GlobalTaxExpense": ("14", "Taxes and licenses"),
    "TaxesPaid": ("14", "Taxes and licenses"),
    "InterestPaid": ("15", "Interest"),
    "Depreciation": ("16a", "Depreciation"),
    "Amortization": ("16a", "Depreciation/Amortization"),
    "Insurance": ("20", "Other deductions: Insurance"),
    "AdvertisingPromotional": ("20", "Other deductions: Advertising"),
    "Auto": ("20", "Other deductions: Auto and truck"),
    "BankCharges": ("20", "Other deductions: Bank charges"),
    "CharitableContributions": ("K-13a", "Schedule K: Charitable contributions"),
    "CommissionsAndFees": ("20", "Other deductions: Commissions"),
    "Entertainment": ("20", "Other deductions: Meals (50% limit)"),
    "EntertainmentMeals": ("20", "Other deductions: Meals (50% limit)"),
    "LegalProfessionalFees": ("20", "Other deductions: Legal & professional"),
    "OfficeExpenses": ("20", "Other deductions: Office expenses"),
    "OfficeGeneralAdministrativeExpenses": ("20", "Other deductions: Office/admin"),
    "Travel": ("20", "Other deductions: Travel"),
    "TravelMeals": ("20", "Other deductions: Travel meals"),
    "Utilities": ("20", "Other deductions: Utilities"),
    "DuesSubscriptions": ("20", "Other deductions: Dues & subscriptions"),
    "ShippingFreightDelivery": ("20", "Other deductions: Postage & delivery"),
    "OtherBusinessExpenses": ("20", "Other deductions"),
    "OtherMiscellaneousExpense": ("20", "Other deductions"),
    "PenaltiesSettlements": ("20", "Other deductions: Penalties"),
    # Schedule K Portfolio Income
    "InterestEarned": ("K-5", "Schedule K: Interest income"),
    "DividendIncome": ("K-6a", "Schedule K: Dividend income"),
    "RentalIncomeReceived": ("K-2", "Schedule K: Rental income"),
    # Balance Sheet
    "Checking": ("L-1", "Cash"),
    "Savings": ("L-1", "Cash"),
    "MoneyMarket": ("L-1", "Cash"),
    "CashOnHand": ("L-1", "Cash"),
    "AccountsReceivable": ("L-2a", "Accounts receivable"),
    "Buildings": ("L-8a", "Depreciable assets"),
    "FurnitureAndFixtures": ("L-8a", "Depreciable assets"),
    "Machinery": ("L-8a", "Depreciable assets"),
    "Vehicles": ("L-8a", "Depreciable assets"),
    "LeaseholdImprovements": ("L-8a", "Depreciable assets"),
    "AccumulatedDepreciation": ("L-8b", "Accumulated depreciation"),
    "Land": ("L-10", "Land"),
    "Goodwill": ("L-11a", "Intangible assets"),
    "OtherLongTermAssets": ("L-12", "Other assets"),
    "OtherCurrentAssets": ("L-12", "Other assets"),
    "PrepaidExpenses": ("L-12", "Other assets"),
    "AccountsPayable": ("L-14", "Accounts payable"),
    "OtherCurrentLiabilities": ("L-19", "Other liabilities"),
    "LongTermDebt": ("L-18", "Long-term mortgage/notes"),
    "NotesPayable": ("L-15", "Short-term mortgage/notes"),
}

SCHEDULE_K_LINES = {
    "K-1": "Ordinary business income (loss)",
    "K-2": "Net rental real estate income (loss)",
    "K-3": "Other net rental income (loss)",
    "K-5": "Interest income",
    "K-6a": "Ordinary dividends",
    "K-6b": "Qualified dividends",
    "K-7": "Royalties",
    "K-8": "Net short-term capital gain (loss)",
    "K-9a": "Net long-term capital gain (loss)",
    "K-10": "Net section 1231 gain (loss)",
    "K-11": "Other income (loss)",
    "K-13a": "Charitable contributions",
    "K-13b": "Investment interest expense",
    "K-16a": "Foreign taxes paid",
    "K-18a": "Tax-exempt interest income",
    "K-18b": "Other tax-exempt income",
    "K-18c": "Nondeductible expenses",
}
